### ISSUE TITLE
Postgresql migration epic

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#2735]
Component parts:

- [ ] all projects should run on new postgresql servers (migrate from `lib-postgres3` and `lib-postgres-prod1` to the new replicated servers, `lib-postgres-prod3` and its replicated box `lib-postgres-prod2`)
- [ ] all projects should upgrade from psql 10 to psql 13 (does this involve code changes?)

Check off when the project has been migrated to the new servers and to psql 13 if necessary. Projects that run on postgres:

- [x] ansible-tower
- [x] approvals [lib-postgres3, pgsql 10]
- [x] approvals-staging [lib-postgres3, pgsql 10]
- [x] bibdata [lib-postgres-prod, pgsql 13]
- [x] cicognara [lib-postgres3, pgsql 10]
- [x] cicognara-staging [lib-postgres3, pgsql 10]
- [x] dpul [lib-postgres3, pgsql 10]
- [x] dpul-staging [lib-postgres3, pgsql 10]
- [x] dss [lib-postgres3, pgsql 10]
- [x] dss-staging [lib-postgres3, pgsql 10]
- [x] figgy [lib-postgres3, pgsql 10]
- [x] figgy-staging [lib-postgres3, pgsql 10]
- [x] geaccirc [lib-postgres3, pgsql 10]
- [x] gscatalog/geoserver (investigate)
- [x] lae [lib-postgres3, pgsql 10]
- [x] lae-staging [lib-postgres3, pgsql 10]
- [x] libjobs [lib-postgres3, pgsql 10]
- [x] lib-jobs-staging [lib-postgres-staging1, pgsql 13]
- [x] libstatistics [lib-postgres3, pgsql 10]
- [x] libstatistics-staging [lib-postgres-staging1, pgsql 13]
- [x] lockers and study spaces [lib-postgres3, pgsql 10]
- [x] lockers and study spaces staging [lib-postgres3, pgsql 10]
- [x] mudd [lib-postgres3, pgsql 10]
- [x] mudd-staging [lib-postgres3, pgsql 10]
- [x] ojs [lib-postgres-prod1, pgsql 13]
- [x] ojs-staging [lib-postgres-staging1, pgsql 13]
- [x] openmonograph
- [x] openmonograph-staging
- [x] ouranos-staging [lib-postgres3, pgsql 10]
- [x] pulfalight [lib-postgres3, pgsql 10]
- [x] pulfalight-staging [lib-postgres3, pgsql 10]
- [x] pulmap [lib-postgres3, pgsql 10]
- [x] pulmap-staging [lib-postgres3, pgsql 10]
- [x] researchdata

Related postgres tickets include #2210 #1522 #2305 #2405 #2444 #2464.
Edit: make the list a checklist.

**Comment by jrgriffiniii** [comment]
`pdc_discovery` may not need to be migrated, but this must be verified.

**Comment by acozine** [comment]
We prioritized migrating services that were connecting to postgres on `lib-postgres-prod1`, which we will retire. All services have migrated EXCEPT the CDH services as of today. Once that goal is met, we will migrate the rest of the services, project by project.

Some projects have staging running on postgresql 13 while production is still running on postgresql 10. These will require extra testing before we migrate and upgrade production.

**Comment by acozine** [comment]
The Ansible Tower database was moved to its own database server running Rocky Linux, see #5606. 
The cicognara project was migrated to a static site, see #5570.
So the only remaining item is gscatalog/geoserver.

**Comment by acozine** [comment]
We migrated gscatalog/geoserver to a lambda on AWS.

**Comment by acozine** [comment]
Remaining work is documented in #4383.
