### ISSUE TITLE
Redirect dss.princeton.edu root URL to library.princeton.edu/dss

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#3065]
Do this after dss app tickets are completed. 

- [x] pulibrary/dss/issues/239
- [x] pulibrary/dss/issues/240
- [x] pulibrary/dss/issues/259  
- [x] #3086

**Comment by kevinreiss** [comment]
Proxy pass rules: https://github.com/pulibrary/princeton_ansible/blob/7aea93d9da020c1ec4739e62bf5368f6ef3bfdab/roles/nginxplus/files/conf/http/templates/dss-proxy-pass.conf
