### ISSUE TITLE
Ruby 2.x EOL 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#3357]
Ruby 2.7 ix End of Life March 31, 2023.

Upgrade to Ruby 3.1 on all apps possible. 

DACS issues:
- [x] https://github.com/pulibrary/bibdata/issues/2000
- [x] https://github.com/pulibrary/orangelight/issues/3209
- [x] https://github.com/pulibrary/mudd-dbs/issues/89
- [x] https://github.com/pulibrary/repecwp/issues/75
- [x] https://github.com/pulibrary/DSS/issues/302
- [x] https://github.com/pulibrary/geaccirc/issues/16
- [x] https://github.com/pulibrary/approvals/issues/819
- [x] https://github.com/pulibrary/lib_jobs/issues/429
- [x] https://github.com/pulibrary/lockers_and_study_spaces/issues/118

DLS issues:
- [x] https://github.com/pulibrary/figgy/issues/5421
- [x] https://github.com/pulibrary/dpul/issues/1394
- [x] https://github.com/pulibrary/lae-blacklight/issues/329
- [x] https://github.com/pulibrary/pulfalight/issues/1125
- [x] https://github.com/pulibrary/pulmap/issues/1112
