### ISSUE TITLE
Move PHP Shared Web Assets Directory to NFS File Mount.

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#3816]
We have a number of Drupal  (Both D7 and D9) applications whose web assets are stored in directories that are currently managed as shared directories via capistrano that reside on the file system of the application server they reside upon. In order to break this dependency web assets should be stored on a file mount separate from the application server file system. Currently the pul_library_drupal and special_collections are implemented using a separate mount our other four Drupal projects should have a similar set-up so application servers can be added or removed as needed. 

Current Staging servers impacted

- [x] library-staging(1,2) new nfs mount: drupal7
- [x] lib-sc-staging1 new nfs mount: drupal7
- [x] fpul-staging1 new nfs mount: drupal7
- [x] byzantine-tsp-staging1 new nfs mount drupal7
- [x] recap-www-staging1 new nfs mount drupal9
- [x] prds-staging1 new nfs mount drupal9
- [x] slavery-staging1 new nfs mount pas

Prod servers to replicate this on once tested

- [x] library-prod(1,2,3)
- [x] lib-sc-prod1
- [x] fpul-prod1
- [x] byzantine-tsp-prod1
- [x] recap-www-prod1 new nfs mount drupal9
- [x] prds-prod1
- [x] slavery-prod1

**Comment by kevinreiss** [comment]
Need to check-in with Francis on where this is at.

**Comment by kevinreiss** [comment]
@kayiwa have we actually done this on prod too?
