### ISSUE TITLE
migrate to jammy solr8

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#4666]
Migrate the configurations of solr8 staging to solr8d staging

related to https://github.com/pulibrary/pul_solr/issues/395

- [x] catalog-qa1 https://github.com/pulibrary/orangelight/issues/3970
- [x] catalog-qa2
- [x] catalog-staging1
- [x] catalog-staging2
- [x] cdh_ppa
- [x] cdh_shxco
- [x] dpul-staging
- [x] figgy-staging pulibrary/figgy#6214
- [x] geniza
- [x] lae-staging2
- [x] library-staging1 https://github.com/pulibrary/pul_library_drupal/issues/2039
- [x] oawaiver-staging
- [x] pdc-discovery-staging-1
- [x] pdc-discovery-staging-2
- [x] pulfalight-qa-1 pulibrary/pulfalight#1384
- [x] pulmap-staging pulibrary/pulmap#1201
- [x] special-collections-staging1 https://github.com/pulibrary/special_collections/issues/773
